title: Björn Schäfer
theme: minima


# This adds li‚nks in the top nav
header_pages:
  - index.md
  - 4_papers.md
  - 3_talks.md
  - 2_teaching.md
  - 5_cv.md

social_links:
  - title: Jekyll repository at GitHub
    icon: github
    url: "https://github.com/jekyll/jekyll"

email: "bschaefer@math.uni-sb.de"
